version: '3.8'

x-base-service: &base
  build:
    context: .
  env_file: .env
  volumes:
    - .:/app
  networks:
    - minha_rede

services:
  web:
    <<: *base
    build:
      context: .
      dockerfile: docker/web.Dockerfile
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8581:8000"
    depends_on:
      - redis
    networks:
      - minha_rede
    dns:
      - 8.8.8.8 
  websocket:
    <<: *base
    build:
      context: .
      dockerfile: docker/websocket.Dockerfile
    command: daphne -b 0.0.0.0 -p 8001 config.asgi:application
    ports:
      - "8582:8001"
    depends_on:
      - redis
    networks:
      - minha_rede

  worker:
    <<: *base
    build:
      context: .
      dockerfile: docker/worker.Dockerfile
    command: celery -A config worker -l info
    depends_on:
      - redis
    networks:
      - minha_rede

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis:/data
    networks:
      - minha_rede

  nginx:
    image: nginx:stable
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8580:80"
    depends_on:
      - web
      - websocket
    networks:
      - minha_rede

volumes:
  redis:

networks:
  minha_rede:
    driver: bridge 
    external: true