version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: docker/web.Dockerfile
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    env_file: .env
    volumes:
      - .:/app
    ports:
      - "8581:8000"
    depends_on:
      - redis
    networks:
      - minha_rede

  websocket:
    build:
      context: .
      dockerfile: docker/websocket.Dockerfile
    command: daphne -b 0.0.0.0 -p 8001 config.asgi:application
    env_file: .env
    volumes:
      - .:/app
    ports:
      - "8582:8001"
    depends_on:
      - redis
    networks:
      - minha_rede

  worker:
    build:
      context: .
      dockerfile: docker/worker.Dockerfile
    command: celery -A config worker --loglevel=info --without-gossip --without-mingle --without-heartbeat --max-tasks-per-child=100
    env_file: .env
    volumes:
      - .:/app
    depends_on:
      - redis
    networks:
      - minha_rede

  redis:
    image: redis:latest
    container_name: redis_mxrouter
    ports:
      - "6481:6481"
    volumes:
      - redis:/data
    networks:
      - minha_rede


  nginx:
    image: nginx:stable
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8580:80"
    depends_on:
      - web
      - websocket
    networks:
      - minha_rede

volumes:
  redis:

networks:
  minha_rede:
    external: true
