# Generated by Django 5.2 on 2025-04-22 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cor', models.CharField(default='#3498db', max_length=7)),
                ('nome', models.CharField(max_length=100, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('paradas', models.IntegerField()),
                ('distancia_km', models.FloatField()),
                ('tempo_min', models.FloatField()),
                ('geojson', models.JSONField()),
                ('pontos', models.JSONField()),
                ('entregas', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='ComposicaoRota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('rotas', models.ManyToManyField(related_name='composicoes', to='ors.rota')),
            ],
        ),
    ]
