# Generated by Django 5.2 on 2025-04-30 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='cpf',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='CPF'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='observation',
            field=models.TextField(blank=True, null=True, verbose_name='Observação'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='reference',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ponto de Referência'),
        ),
        migrations.AddField(
            model_name='historicaldelivery',
            name='cpf',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='CPF'),
        ),
        migrations.AddField(
            model_name='historicaldelivery',
            name='observation',
            field=models.TextField(blank=True, null=True, verbose_name='Observação'),
        ),
        migrations.AddField(
            model_name='historicaldelivery',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone'),
        ),
        migrations.AddField(
            model_name='historicaldelivery',
            name='reference',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ponto de Referência'),
        ),
    ]
