# Generated by Django 5.2 on 2025-05-06 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalroutearea',
            name='areatotal',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalroutearea',
            name='kmtotal',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='routearea',
            name='areatotal',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='routearea',
            name='kmtotal',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
