# Generated by Django 5.2 on 2025-04-30 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmsapp', '0002_delivery_cpf_delivery_observation_delivery_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='historicaldelivery',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço'),
        ),
    ]
