# Generated by Django 5.2 on 2025-04-30 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmsapp', '0003_delivery_address_historicaldelivery_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='historicaldelivery',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='CEP'),
        ),
    ]
