# Generated by Django 5.2 on 2025-05-02 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmsapp', '0004_delivery_postal_code_historicaldelivery_postal_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='route_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Rota'),
        ),
        migrations.AddField(
            model_name='historicaldelivery',
            name='route_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Rota'),
        ),
    ]
