# Generated by Django 5.2 on 2025-05-03 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmsapp', '0005_delivery_route_name_historicaldelivery_route_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='is_check',
            field=models.BooleanField(default=False, verbose_name='Marcado no Mapa'),
        ),
        migrations.AddField(
            model_name='historicaldelivery',
            name='is_check',
            field=models.BooleanField(default=False, verbose_name='Marcado no Mapa'),
        ),
    ]
