# Generated by Django 5.2 on 2025-05-03 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmsapp', '0006_delivery_is_check_historicaldelivery_is_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='is_check',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Marcado no Mapa'),
        ),
        migrations.AlterField(
            model_name='historicaldelivery',
            name='is_check',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Marcado no Mapa'),
        ),
    ]
