# Generated by Django 5.2 on 2025-05-04 02:23

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmsapp', '0007_alter_delivery_is_check_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalRouteArea',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('geojson', models.TextField(blank=True, null=True)),
                ('neighborhoods', models.JSONField(blank=True, default=list)),
                ('cities', models.JSONField(blank=True, default=list)),
                ('cep_start', models.JSONField(blank=True, default=list)),
                ('cep_end', models.JSONField(blank=True, default=list)),
                ('color_name', models.CharField(choices=[('orange', 'Laranja'), ('green', 'Verde'), ('blue', 'Azul'), ('purple', 'Roxo'), ('darkred', 'Vermelho Escuro'), ('darkgreen', 'Verde Escuro'), ('darkblue', 'Azul Escuro'), ('cadetblue', 'Azul Cadete'), ('lightred', 'Vermelho Claro'), ('beige', 'Bege'), ('lightgreen', 'Verde Claro'), ('lightblue', 'Azul Claro'), ('darkpurple', 'Roxo Escuro'), ('pink', 'Rosa'), ('gray', 'Cinza')], default='blue', help_text='Color name for map area (e.g., blue, green)', max_length=20)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Updated At')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Route Area',
                'verbose_name_plural': 'historical Route Areas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='RouteArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('geojson', models.TextField(blank=True, null=True)),
                ('neighborhoods', models.JSONField(blank=True, default=list)),
                ('cities', models.JSONField(blank=True, default=list)),
                ('cep_start', models.JSONField(blank=True, default=list)),
                ('cep_end', models.JSONField(blank=True, default=list)),
                ('color_name', models.CharField(choices=[('orange', 'Laranja'), ('green', 'Verde'), ('blue', 'Azul'), ('purple', 'Roxo'), ('darkred', 'Vermelho Escuro'), ('darkgreen', 'Verde Escuro'), ('darkblue', 'Azul Escuro'), ('cadetblue', 'Azul Cadete'), ('lightred', 'Vermelho Claro'), ('beige', 'Bege'), ('lightgreen', 'Verde Claro'), ('lightblue', 'Azul Claro'), ('darkpurple', 'Roxo Escuro'), ('pink', 'Rosa'), ('gray', 'Cinza')], default='blue', help_text='Color name for map area (e.g., blue, green)', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='route_areas_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Route Area',
                'verbose_name_plural': 'Route Areas',
                'db_table': 'route_area',
            },
        ),
    ]
